/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import factory.ConexaoFactory;
import bean.AlunoBean;
import bean.CaixaBean;
import bean.ContratoBean;
import bean.ParcelasBean;
import dao.CaixaDAO;
import dao.ContratoDAO;
import dao.ParcelasDAO;
import de.javasoft.plaf.synthetica.SyntheticaPlainLookAndFeel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ronaldo Pedro
 */
public class JDBaixaContratoEmpresa extends javax.swing.JDialog {

    private java.sql.Connection con;
    private java.sql.Statement stmtListar;
    private java.sql.ResultSet rsListar;
    ConexaoFactory conecta = new ConexaoFactory();
    JDBancoBaixa banco = new JDBancoBaixa(null, rootPaneCheckingEnabled);

    /**
     * Creates new form JDEmprestimo
     */
    public JDBaixaContratoEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lookandfell();
        jFormattedTextFieldCNPJ.requestFocus();
        jRadioButtonEmAberto.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItensEmprestimo = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonEfetuarBaixa = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableParcelas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNomeFantasiaDados = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldEmailAlunoDados = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldID_Aluno = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldEnderecoAlunoDados = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldBairroAlunoDados = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldCNPJDados = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIE = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldCidadeAlunoDados = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableContrato = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jRadioButtonEmAberto = new javax.swing.JRadioButton();
        jRadioButtonBaixados = new javax.swing.JRadioButton();
        jRadioButtonAmbos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        precoRender1 = new util.PrecoRender();
        dataRender1 = new util.DataRender();
        jButtonBusca = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();

        jTableItensEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Livro", "ISBN", "Titulo / Obra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableItensEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItensEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableItensEmprestimo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baixa de Mensalidade Contratos");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Baixa de Documentos Pendentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setFocusCycleRoot(true);

        jButtonEfetuarBaixa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEfetuarBaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/ok_button.png"))); // NOI18N
        jButtonEfetuarBaixa.setText("Efetuar Baixa");
        jButtonEfetuarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEfetuarBaixaActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/limpar_icon.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/delete_button_1.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("CNPJ");

        jTableParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nº PC", "Nº Contrato", "Nº Parcela", "Tipo Pagamento", "Valor", "Data Vencimento", "Data Baixa", "Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableParcelas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableParcelas.getTableHeader().setReorderingAllowed(false);
        jTableParcelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableParcelasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableParcelas);
        if (jTableParcelas.getColumnModel().getColumnCount() > 0) {
            jTableParcelas.getColumnModel().getColumn(4).setCellRenderer(precoRender1);
            jTableParcelas.getColumnModel().getColumn(5).setCellRenderer(dataRender1);
            jTableParcelas.getColumnModel().getColumn(6).setCellRenderer(dataRender1);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do Aluno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Nome Fantasia");

        jTextFieldNomeFantasiaDados.setEditable(false);
        jTextFieldNomeFantasiaDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNomeFantasiaDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFantasiaDadosActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Email");

        jTextFieldEmailAlunoDados.setEditable(false);
        jTextFieldEmailAlunoDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEmailAlunoDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailAlunoDadosFocusLost(evt);
            }
        });
        jTextFieldEmailAlunoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailAlunoDadosActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Telefone");

        jFormattedTextFieldTelefone.setEditable(false);
        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel23.setText("ID");

        jTextFieldID_Aluno.setEditable(false);
        jTextFieldID_Aluno.setBorder(null);
        jTextFieldID_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID_AlunoActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Endereço");

        jTextFieldEnderecoAlunoDados.setEditable(false);
        jTextFieldEnderecoAlunoDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEnderecoAlunoDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnderecoAlunoDadosFocusLost(evt);
            }
        });
        jTextFieldEnderecoAlunoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoAlunoDadosActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Bairro");

        jTextFieldBairroAlunoDados.setEditable(false);
        jTextFieldBairroAlunoDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBairroAlunoDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroAlunoDadosFocusLost(evt);
            }
        });
        jTextFieldBairroAlunoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroAlunoDadosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CNPJ");

        jFormattedTextFieldCNPJDados.setEditable(false);
        try {
            jFormattedTextFieldCNPJDados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNPJDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("IE");

        jTextFieldIE.setEditable(false);
        jTextFieldIE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Cidade");

        jTextFieldCidadeAlunoDados.setEditable(false);
        jTextFieldCidadeAlunoDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCidadeAlunoDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeAlunoDadosFocusLost(evt);
            }
        });
        jTextFieldCidadeAlunoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeAlunoDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCidadeAlunoDados)
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldCNPJDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(jTextFieldIE, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29)
                            .addComponent(jTextFieldNomeFantasiaDados, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldEnderecoAlunoDados))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldEmailAlunoDados)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldBairroAlunoDados)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldID_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldID_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeFantasiaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmailAlunoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnderecoAlunoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairroAlunoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidadeAlunoDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFormattedTextFieldCNPJDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Contratos da Empresa");

        jTableContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nº Contrato", "Plano", "Valor Mensal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableContrato.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableContrato.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableContrato);
        if (jTableContrato.getColumnModel().getColumnCount() > 0) {
            jTableContrato.getColumnModel().getColumn(2).setCellRenderer(precoRender1);
        }

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Considerar Titulos");

        buttonGroup1.add(jRadioButtonEmAberto);
        jRadioButtonEmAberto.setText("Em Aberto");
        jRadioButtonEmAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmAbertoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonBaixados);
        jRadioButtonBaixados.setText("Baixados");
        jRadioButtonBaixados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBaixadosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonAmbos);
        jRadioButtonAmbos.setText("Ambos");
        jRadioButtonAmbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAmbosActionPerformed(evt);
            }
        });

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonBusca.setText("P");
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir Lançamento");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNPJ.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextFieldCNPJ.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jFormattedTextFieldCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCNPJFocusLost(evt);
            }
        });
        jFormattedTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCNPJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEfetuarBaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimpar)
                        .addGap(472, 472, 472)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonSair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(dataRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jButtonBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonEmAberto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonBaixados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonAmbos))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jButtonBusca)
                            .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonEmAberto)
                        .addComponent(jRadioButtonBaixados)
                        .addComponent(jLabel24)
                        .addComponent(jRadioButtonAmbos)
                        .addComponent(jButton1)
                        .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dataRender1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEfetuarBaixa)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOuvinteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOuvinteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOuvinteFocusLost

    private void jTextFieldOuvinteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldOuvinteInputMethodTextChanged

    }//GEN-LAST:event_jTextFieldOuvinteInputMethodTextChanged

    private void jTextFieldOuvinteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOuvinteKeyPressed

    }//GEN-LAST:event_jTextFieldOuvinteKeyPressed

    private void jTextFieldOuvinteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOuvinteKeyReleased

    }//GEN-LAST:event_jTextFieldOuvinteKeyReleased

    private void jTableItensEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItensEmprestimoMouseClicked

    }//GEN-LAST:event_jTableItensEmprestimoMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
//        montarTabela();
    }//GEN-LAST:event_formFocusGained

    private void jTableParcelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableParcelasMouseClicked
        int linha = jTableParcelas.getSelectedRow();
//        jTextFieldIDEmprestimo.setText(jTableParcelas.getValueAt(linha, 3).toString());
//        jTextFieldISBN.setText(jTableParcelas.getValueAt(linha, 4).toString());
//        jTextFieldIDLivro.setText(jTableParcelas.getValueAt(linha, 7).toString());
//        jTextFieldIdItem.setText(jTableParcelas.getValueAt(linha, 8).toString());
    }//GEN-LAST:event_jTableParcelasMouseClicked

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
//        limparCampos();

        limparCampos();
        limparTabelaContrato();
        limparTabelaParcelas();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonEfetuarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfetuarBaixaActionPerformed
        int linha = jTableParcelas.getSelectedRow();
        int option = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Baixar este Titulo ?");
        if (option == JOptionPane.YES_OPTION) {
            if (jTableParcelas.getValueAt(linha, 6) == "Em Aberto") {
                JDBancoBaixa bancobaixa = new JDBancoBaixa(null, rootPaneCheckingEnabled);
                bancobaixa.setLocationRelativeTo(null);
                bancobaixa.setVisible(true);

                if (JDBancoBaixa.status == 1) {
                    EfetuarBaixa();
                } else {
                    this.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Não Foi Possivel Fazer a Baixa \n Titulo já está baixado !!");
            }

        }

    }//GEN-LAST:event_jButtonEfetuarBaixaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
//        Date hoje = new Date();
//        SimpleDateFormat df;
//        df = new SimpleDateFormat("dd/MM/yyyy");
//        jFormattedTextFieldDataLocal.setText(df.format(hoje));
//        System.out.println("src.JDBaixaEmprestimo.formWindowGainedFocus()");
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTextFieldNomeFantasiaDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFantasiaDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFantasiaDadosActionPerformed

    private void jTextFieldEmailAlunoDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailAlunoDadosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailAlunoDadosFocusLost

    private void jTextFieldEmailAlunoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailAlunoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailAlunoDadosActionPerformed

    private void jTextFieldID_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID_AlunoActionPerformed

    private void jTextFieldEnderecoAlunoDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoAlunoDadosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoAlunoDadosFocusLost

    private void jTextFieldEnderecoAlunoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoAlunoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoAlunoDadosActionPerformed

    private void jTextFieldBairroAlunoDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroAlunoDadosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroAlunoDadosFocusLost

    private void jTextFieldBairroAlunoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroAlunoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroAlunoDadosActionPerformed

    private void jTextFieldCidadeAlunoDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeAlunoDadosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeAlunoDadosFocusLost

    private void jTextFieldCidadeAlunoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeAlunoDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeAlunoDadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(0);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(30);
        if (jRadioButtonEmAberto.isSelected() == true) {
            montarParcelasEmAberto();
        } else {
            montarParcelas();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonEmAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmAbertoActionPerformed
        // TODO add your handling code here:
        jButtonEfetuarBaixa.setEnabled(true);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(0);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(30);
        montarParcelasEmAberto();
    }//GEN-LAST:event_jRadioButtonEmAbertoActionPerformed

    private void jRadioButtonBaixadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBaixadosActionPerformed
        // TODO add your handling code here:
        jButtonEfetuarBaixa.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(0);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(30);
        montarParcelasBaixados();
    }//GEN-LAST:event_jRadioButtonBaixadosActionPerformed

    private void jRadioButtonAmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAmbosActionPerformed
        // TODO add your handling code here:
        jButtonExcluir.setEnabled(false);
        jButtonEfetuarBaixa.setEnabled(false);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(0);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(30);
        montarParcelas();
    }//GEN-LAST:event_jRadioButtonAmbosActionPerformed

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        // TODO add your handling code here:
        limparCampos();
        limparTabelaContrato();
        limparTabelaParcelas();
        JDPesquisaGlobalFornecedor pesquisa = new JDPesquisaGlobalFornecedor(null, rootPaneCheckingEnabled);
        pesquisa.setLocationRelativeTo(null);
        pesquisa.setVisible(true);
        jFormattedTextFieldCNPJ.setText(pesquisa.cpf);
        jFormattedTextFieldCNPJ.requestFocus();
    }//GEN-LAST:event_jButtonBuscaActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int linha = jTableParcelas.getSelectedRow();
        if (jTableParcelas.getValueAt(linha, 0) == null) {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma Linha preenchida !!");
        } else {

            try {

                ParcelasBean parcela = new ParcelasBean();
                ParcelasDAO dao = new ParcelasDAO();

                String idstr = jTableParcelas.getValueAt(linha, 0).toString();
                int id = Integer.parseInt(idstr);
                parcela.setId_parcela_contrato(id);
                Integer opcao = JOptionPane.showConfirmDialog(null, "Confirma a Exclusão do Titutlo?", "Excluir Titulo", JOptionPane.OK_CANCEL_OPTION);
                if (opcao == JOptionPane.YES_OPTION) {
                    dao.excluirLancamentoEmpresa(parcela);
                    ((DefaultTableModel) jTableParcelas.getModel()).removeRow(jTableParcelas.getSelectedRow());

                } else {

                }
            } catch (ClassNotFoundException | NumberFormatException | SQLException e) {

            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jFormattedTextFieldCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jFormattedTextFieldCNPJFocusGained

    private void jFormattedTextFieldCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJFocusLost
        if (jFormattedTextFieldCNPJ.getText().equals("   .   .   -  ")) {

        } else {

            buscarCPF();
            buscarContrato();
            limparTabelaParcelas();
        }


    }//GEN-LAST:event_jFormattedTextFieldCNPJFocusLost

    private void jFormattedTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCNPJActionPerformed

    private void EfetuarBaixa() {
        int linha = jTableParcelas.getSelectedRow();
        ParcelasBean parcelas = new ParcelasBean();
        ParcelasDAO dao = new ParcelasDAO();
        CaixaBean caixa = new CaixaBean();
        CaixaDAO daoc = new CaixaDAO();
        Date data_criacao = new Date();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(data_criacao.getTime());
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");

        try {
            String idstr = jTableParcelas.getValueAt(linha, 0).toString();
            String tipo_movimento = "E";
            String tipo_pagamento = String.valueOf(jTableParcelas.getValueAt(linha, 3));
            Object data_lancamento = jTableParcelas.getValueAt(linha, 5);
            String historico = "Pagamento de Mensalidade. - Empresa: " + jTextFieldNomeFantasiaDados.getText() + "";
            String valorstr = jTableParcelas.getValueAt(linha, 4).toString();
            Double valor = Double.parseDouble(valorstr);

            caixa.setTipo_movimento(tipo_movimento);
            caixa.setTipo_pagamento(tipo_pagamento);
            caixa.setData_lancamento(data_criacao);
            caixa.setHora_lancamento(timestamp);
            caixa.setHistorico(historico);
            caixa.setValor(valor);
            caixa.setId_titulo(Integer.parseInt(idstr));
            caixa.setCaixa(JDBancoBaixa.nome_banco);
            caixa.setId_banco(JDBancoBaixa.id_banco);
            caixa.setId_tipo(4);
            caixa.setId_fornecedor(Integer.parseInt(jTextFieldID_Aluno.getText()));
            caixa.setId_aluno(1);
            parcelas.setId_parcela_contrato(Integer.parseInt(idstr));
            parcelas.setData_baixa(data_criacao);

            dao.efetuarBaixa(parcelas);
            daoc.inserir(caixa);
            JOptionPane.showMessageDialog(rootPane, "Aguarde ... \n Gerando Recibo !!");
            gerarreciboJD();
            ((DefaultTableModel) jTableParcelas.getModel()).removeRow(jTableParcelas.getSelectedRow());

            jFormattedTextFieldCNPJ.setText("");
            jFormattedTextFieldCNPJ.requestFocus();

        } catch (NumberFormatException | SQLException e) {

        }
    }

    private void buscarCPF() {
        try {
            AlunoBean aluno = new AlunoBean();
            aluno.setCpf(jFormattedTextFieldCNPJ.getText());
            iniciarBD();
            rsListar = stmtListar.executeQuery("SELECT * FROM cad_empresa WHERE cnpj='" + jFormattedTextFieldCNPJ.getText() + "'");

            if (rsListar.next()) {
                jTextFieldID_Aluno.setText(rsListar.getString(1));
                jTextFieldNomeFantasiaDados.setText(rsListar.getString(2));

                jTextFieldEmailAlunoDados.setText(rsListar.getString(7));
                jFormattedTextFieldTelefone.setText(rsListar.getString(10));

                jTextFieldEnderecoAlunoDados.setText(rsListar.getString(4));
                jTextFieldBairroAlunoDados.setText(rsListar.getString(5));
                jTextFieldCidadeAlunoDados.setText(rsListar.getString(6));
                jFormattedTextFieldCNPJDados.setText(rsListar.getString(8));
                jTextFieldIE.setText(rsListar.getString(9));

            } else if (!jFormattedTextFieldCNPJ.equals("  .   .   /    -  ")) {

            }
            if (!jFormattedTextFieldCNPJ.getText().equals("  .   .   /    -  ") && (!rsListar.first())) {
                JOptionPane.showMessageDialog(null, "Empresa Não cadastrado para este CNPJ!!");
                jFormattedTextFieldCNPJ.requestFocus();
                jFormattedTextFieldCNPJ.setText("");
            }

        } catch (SQLException ex) {

        }
    }

    private void montarTabelaContrato() {
        System.out.println("PASSOU");
        int linha = 0;
        try {
            while (rsListar.next()) {
                String id_contrato = rsListar.getString("contrato_empresa.id_contrato_empresa");
                String plano = rsListar.getString("cad_plano.nome");
                Double valor = rsListar.getDouble("contrato_empresa.valor_mensal");

                jTableContrato.getModel().setValueAt(id_contrato, linha, 0);
                jTableContrato.getModel().setValueAt(plano, linha, 1);
                jTableContrato.getModel().setValueAt(valor, linha, 2);

                linha++;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
        }
    }

    private void buscarContrato() {
        iniciarBD();
        try {
            if (jFormattedTextFieldCNPJ.getText().equals("  .   .   /    -  ")) {

            } else {

                int id_titular = Integer.parseInt(jTextFieldID_Aluno.getText());
                rsListar = stmtListar.executeQuery("SELECT\n"
                        + "                    contrato_empresa.id_empresa,\n"
                        + "                  contrato_empresa.valor_mensal ,\n"
                        + "                    cad_plano.id_plano ,\n"
                        + "                    cad_plano.nome ,\n"
                        + "                    contrato_empresa.id_plano,\n"
                        + "                    contrato_empresa.id_contrato_empresa\n"
                        + "                    FROM\n"
                        + "                    contrato_empresa contrato_empresa INNER JOIN cad_plano cad_plano ON contrato_empresa.id_plano = cad_plano.id_plano where contrato_empresa.id_empresa='" + id_titular + "'");
                montarTabelaContrato();
            }
        } catch (SQLException ex) {

        }

    }

    private void montarParcelas() {
        try {
            int indiceLinha = jTableContrato.getSelectedRow();
            Object id = jTableContrato.getValueAt(indiceLinha, 0);
            System.out.println(id);
            iniciarBD();
            rsListar = stmtListar.executeQuery("select * from parcela_contrato_empresa where id_parcela_contrato_empresa= '" + id + "' order by data_baixa asc");
            montarTabela();
        } catch (Exception e) {
        }
    }

    private void montarParcelasBaixados() {
        try {
            int indiceLinha = jTableContrato.getSelectedRow();
            Object id = jTableContrato.getValueAt(indiceLinha, 0);
            System.out.println(id);
            iniciarBD();
            rsListar = stmtListar.executeQuery("select * from parcela_contrato_empresa where id_parcela_contrato_empresa= '" + id + "' and data_baixa IS NOT NULL order by data_baixa asc");
            montarTabela();
        } catch (Exception e) {
        }
    }

    private void montarParcelasEmAberto() {
        try {
            int indiceLinha = jTableContrato.getSelectedRow();
            Object id = jTableContrato.getValueAt(indiceLinha, 0);
            System.out.println(id);
            iniciarBD();
            rsListar = stmtListar.executeQuery("select * from parcela_contrato_empresa where id_parcela_contrato_empresa= '" + id + "' and data_baixa IS NULL order by data_baixa asc");
            montarTabela();
        } catch (Exception e) {
        }
    }

    private void montarTabela() {
        int linha = 0;
//         jTableParcelas.setDefaultRenderer(Double.class,);
        try {
            while (rsListar.next()) {
                int numero_parcela_contrato = rsListar.getInt(1);
                int id_contrato = rsListar.getInt(2);
                int numero_parcelas = rsListar.getInt(3);
                String tipo_pgto = rsListar.getString("tipo_pagamento");
                Double valor = rsListar.getDouble(4);
                Date data_vecimento = rsListar.getDate("data_vencimento");
                Date data_baixa = rsListar.getDate("data_baixa");
                String usuario = rsListar.getString("usuario");

                jTableParcelas.getModel().setValueAt(numero_parcela_contrato, linha, 0);
                jTableParcelas.getModel().setValueAt(id_contrato, linha, 1);
                jTableParcelas.getModel().setValueAt(numero_parcelas, linha, 2);
                jTableParcelas.getModel().setValueAt(tipo_pgto, linha, 3);
                jTableParcelas.getModel().setValueAt(valor, linha, 4);
                jTableParcelas.getModel().setValueAt(data_vecimento, linha, 5);
                jTableParcelas.getModel().setValueAt(data_baixa, linha, 6);
                jTableParcelas.getModel().setValueAt(usuario, linha, 7);

                if (data_baixa == null) {
                    jTableParcelas.getModel().setValueAt("Em Aberto", linha, 6);
                }

                linha++;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
        }
    }

    private void gerarreciboJD() {
        int linha = jTableParcelas.getSelectedRow();
        String id_titulo_str = jTableParcelas.getValueAt(linha, 0).toString();
        String id_contratostr = jTableContrato.getValueAt(linha, 0).toString();
        int id_titulo = Integer.parseInt(id_titulo_str);
        int id_contrato = Integer.parseInt(id_contratostr);
        int id_fornecedor = Integer.parseInt(jTextFieldID_Aluno.getText());

        try {

            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Dimension screenSize = toolkit.getScreenSize();

            JDialog viewer = new JDialog(new javax.swing.JFrame(), "Visualização do Recibo", true);

            viewer.setBounds(0, 0, screenSize.width, screenSize.height);
            viewer.setLocationRelativeTo(null);
            conecta.executaSQL("SELECT\n"
                    + "     caixa.`id_caixa` AS caixa_id_caixa,\n"
                    + "     caixa.`tipo_movimento` AS caixa_tipo_movimento,\n"
                    + "     caixa.`tipo_pagamento` AS caixa_tipo_pagamento,\n"
                    + "     caixa.`data_lancamento` AS caixa_data_lancamento,\n"
                    + "     caixa.`hora_lancamento` AS caixa_hora_lancamento,\n"
                    + "     caixa.`historico` AS caixa_historico,\n"
                    + "     caixa.`valor` AS caixa_valor,\n"
                    + "     caixa.`id_titulo` AS caixa_id_titulo,\n"
                    + "     caixa.`nome_caixa` AS caixa_nome_caixa,\n"
                    + "     caixa.`id_banco` AS caixa_id_banco,\n"
                    + "     cad_plano.`id_plano` AS cad_plano_id_plano,\n"
                    + "     cad_plano.`nome` AS cad_plano_nome,\n"
                    + "     caixa.`id_aluno` AS caixa_id_aluno,\n"
                    + "     cad_empresa.`id_empresa` AS cad_empresa_id_empresa,\n"
                    + "     cad_empresa.`nome_fantasia` AS cad_empresa_nome_fantasia,\n"
                    + "     cad_empresa.`razao_social` AS cad_empresa_razao_social,\n"
                    + "     cad_empresa.`endereco` AS cad_empresa_endereco,\n"
                    + "     cad_empresa.`bairro` AS cad_empresa_bairro,\n"
                    + "     cad_empresa.`cidade` AS cad_empresa_cidade,\n"
                    + "     cad_empresa.`email` AS cad_empresa_email,\n"
                    + "     cad_empresa.`cnpj` AS cad_empresa_cnpj,\n"
                    + "     cad_empresa.`inscricao_estadual` AS cad_empresa_inscricao_estadual,\n"
                    + "     cad_empresa.`telefone` AS cad_empresa_telefone,\n"
                    + "     cad_empresa.`ativo` AS cad_empresa_ativo,\n"
                    + "     parcela_contrato_empresa.`id_parcela_contrato_empresa` AS parcela_contrato_empresa_id_parcela_contrato_empresa,\n"
                    + "     parcela_contrato_empresa.`id_contrato` AS parcela_contrato_empresa_id_contrato,\n"
                    + "     parcela_contrato_empresa.`numero_parcela` AS parcela_contrato_empresa_numero_parcela,\n"
                    + "     parcela_contrato_empresa.`valor_parcela` AS parcela_contrato_empresa_valor_parcela,\n"
                    + "     parcela_contrato_empresa.`data_vencimento` AS parcela_contrato_empresa_data_vencimento,\n"
                    + "     parcela_contrato_empresa.`data_baixa` AS parcela_contrato_empresa_data_baixa,\n"
                    + "     parcela_contrato_empresa.`usuario` AS parcela_contrato_empresa_usuario,\n"
                    + "     parcela_contrato_empresa.`tipo_pagamento` AS parcela_contrato_empresa_tipo_pagamento,\n"
                    + "     parcela_contrato_empresa.`tipo_entrada` AS parcela_contrato_empresa_tipo_entrada,\n"
                    + "     parcela_contrato_empresa.`valor_total` AS parcela_contrato_empresa_valor_total,\n"
                    + "     contrato_empresa.`id_contrato_empresa` AS contrato_empresa_id_contrato_empresa,\n"
                    + "     contrato_empresa.`id_empresa` AS contrato_empresa_id_empresa,\n"
                    + "     contrato_empresa.`id_plano` AS contrato_empresa_id_plano,\n"
                    + "     contrato_empresa.`id_item_plano` AS contrato_empresa_id_item_plano,\n"
                    + "     contrato_empresa.`data_adesao` AS contrato_empresa_data_adesao,\n"
                    + "     contrato_empresa.`data_criacao` AS contrato_empresa_data_criacao,\n"
                    + "     contrato_empresa.`usuario` AS contrato_empresa_usuario,\n"
                    + "     contrato_empresa.`total_parcelas` AS contrato_empresa_total_parcelas,\n"
                    + "     contrato_empresa.`valor_total` AS contrato_empresa_valor_total,\n"
                    + "     contrato_empresa.`valor_mensal` AS contrato_empresa_valor_mensal,\n"
                    + "     contrato_empresa.`status` AS contrato_empresa_status,\n"
                    + "     caixa.`id_fornecedor` AS caixa_id_fornecedor\n"
                    + "FROM\n"
                    + "     `cad_empresa` cad_empresa INNER JOIN `contrato_empresa` contrato_empresa ON cad_empresa.`id_empresa` = contrato_empresa.`id_empresa`\n"
                    + "     INNER JOIN `caixa` caixa ON contrato_empresa.`id_empresa` = caixa.`id_fornecedor`\n"
                    + "     INNER JOIN `cad_plano` cad_plano ON contrato_empresa.`id_plano` = cad_plano.`id_plano`\n"
                    + "     INNER JOIN `parcela_contrato_empresa` parcela_contrato_empresa ON contrato_empresa.`id_contrato_empresa` = parcela_contrato_empresa.`id_contrato`\n"
                    + "     AND caixa.`id_titulo` = parcela_contrato_empresa.`id_parcela_contrato_empresa`\n"
                    + "WHERE\n"
                    + "     contrato_empresa.id_contrato_empresa ='" + id_contrato + "'\n"
                    + "     and parcela_contrato_empresa.id_parcela_contrato_empresa = '" + id_titulo + "'");
            JRResultSetDataSource relatResult = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("C:\\Program Files\\Movimente\\MoviMente\\src\\relatorios\\recibovenda_empresa.jasper", new HashMap(), relatResult);
            JasperViewer jv = new JasperViewer(jpPrint, false);
            viewer.getContentPane().add(jv.getContentPane());
            viewer.setVisible(true);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao chamar o Relatorio! \nErro:" + e);
        }
    }

    private void limparCampos() {

        jTextFieldBairroAlunoDados.setText("");
        jTextFieldCidadeAlunoDados.setText("");
        jTextFieldIE.setText("");
        jTextFieldNomeFantasiaDados.setText("");
        jTextFieldID_Aluno.setText("");
        jTextFieldEmailAlunoDados.setText("");
        jTextFieldEnderecoAlunoDados.setText("");
        jFormattedTextFieldCNPJ.setText(null);
        jFormattedTextFieldCNPJDados.setText(null);
        jFormattedTextFieldTelefone.setText(null);

    }

    private void limparTabelaContrato() {

        ((DefaultTableModel) jTableContrato.getModel()).setNumRows(0);
        ((DefaultTableModel) jTableContrato.getModel()).setNumRows(8);

    }

    private void limparTabelaParcelas() {

        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(0);
        ((DefaultTableModel) jTableParcelas.getModel()).setNumRows(15);

    }

    private void limparCampos2() {

    }

    private void lookandfell() {
        try {

            UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ParseException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o tema = " + erro);
        }
    }

    private void iniciarBD() {
        try {
            con = ConexaoFactory.getConnection();
            stmtListar = con.createStatement();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBaixaContratoEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBaixaContratoEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBaixaContratoEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBaixaContratoEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDBaixaContratoEmpresa dialog = new JDBaixaContratoEmpresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private util.DataRender dataRender1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JButton jButtonEfetuarBaixa;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJDados;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonAmbos;
    private javax.swing.JRadioButton jRadioButtonBaixados;
    private javax.swing.JRadioButton jRadioButtonEmAberto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableContrato;
    private javax.swing.JTable jTableItensEmprestimo;
    private javax.swing.JTable jTableParcelas;
    private javax.swing.JTextField jTextFieldBairroAlunoDados;
    private javax.swing.JTextField jTextFieldCidadeAlunoDados;
    private javax.swing.JTextField jTextFieldEmailAlunoDados;
    private javax.swing.JTextField jTextFieldEnderecoAlunoDados;
    private javax.swing.JTextField jTextFieldID_Aluno;
    private javax.swing.JTextField jTextFieldIE;
    private javax.swing.JTextField jTextFieldNomeFantasiaDados;
    private util.PrecoRender precoRender1;
    // End of variables declaration//GEN-END:variables
}
