/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import bean.AlunoBean;
import dao.AlunoDAO;
import de.javasoft.plaf.synthetica.SyntheticaPlainLookAndFeel;
import factory.ConexaoFactory;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ronaldo Pedro
 */
public class JDCadAluno extends javax.swing.JDialog {

    String look_and_fell = ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    int ativo = 1;
    ConexaoFactory conecta = new ConexaoFactory();
    private java.sql.Connection con;
    private java.sql.Statement stmtListar;
    private java.sql.ResultSet rsListar;
    public static int tipo;
    public static int id_aluno;

    /**
     * Creates new form NovoJDialog
     */
    public JDCadAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lookandfell();
        bloqueiaCamposTitular();
        jCheckBoxAtivo.setSelected(true);
        this.setModal(true);
        jButtonBusca.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jDateChooserDataNasc = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jCheckBoxAtivo = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxDependente = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldNomeTitular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldCPFTitular = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldTelefoneTitular = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldEmailTitular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRGTitular = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldIDTitular = new javax.swing.JTextField();
        jButtonBusca = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldId_Aluno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movi Mente - Cadastro de Alunos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastrar Novo Aluno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Telefone");

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jbCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/save_f.png"))); // NOI18N
        jbCadastrar.setText("Salvar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/limpar_icon.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/delete_button.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("CPF");

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFormattedTextFieldCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jFormattedTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCPFFocusLost(evt);
            }
        });
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Cidade");

        jTextFieldCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeFocusLost(evt);
            }
        });
        jTextFieldCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Endereco");

        jTextFieldEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnderecoFocusLost(evt);
            }
        });
        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Data Nascimento");

        jDateChooserDataNasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Ativo");

        jCheckBoxAtivo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Bairro");

        jTextFieldBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });
        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Dependente?");

        jComboBoxDependente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Sim", "Não" }));
        jComboBoxDependente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDependenteItemStateChanged(evt);
            }
        });
        jComboBoxDependente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxDependenteFocusLost(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do Titular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTextFieldNomeTitular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNomeTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeTitularActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nome");

        try {
            jFormattedTextFieldCPFTitular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPFTitular.setFocusLostBehavior(javax.swing.JFormattedTextField.REVERT);
        jFormattedTextFieldCPFTitular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jFormattedTextFieldCPFTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCPFTitularFocusLost(evt);
            }
        });
        jFormattedTextFieldCPFTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFTitularActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("CPF");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Telefone");

        try {
            jFormattedTextFieldTelefoneTitular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefoneTitular.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFormattedTextFieldTelefoneTitular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Email");

        jTextFieldEmailTitular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEmailTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailTitularFocusLost(evt);
            }
        });
        jTextFieldEmailTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailTitularActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("RG");

        jTextFieldRGTitular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldRGTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRGTitularFocusLost(evt);
            }
        });
        jTextFieldRGTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRGTitularActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setText("ID");

        jTextFieldIDTitular.setEditable(false);
        jTextFieldIDTitular.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextFieldIDTitular.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldIDTitularCaretUpdate(evt);
            }
        });
        jTextFieldIDTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIDTitularFocusLost(evt);
            }
        });
        jTextFieldIDTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDTitularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(190, 190, 190))
                                .addComponent(jTextFieldNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmailTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jFormattedTextFieldTelefoneTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldCPFTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldRGTitular)
                                    .addComponent(jLabel10)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIDTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldIDTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCPFTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(25, 25, 25))
                    .addComponent(jTextFieldRGTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(25, 25, 25))
                    .addComponent(jFormattedTextFieldTelefoneTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldEmailTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonBusca.setText("P");
        jButtonBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonBuscaFocusLost(evt);
            }
        });
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setText("ID Aluno");

        jTextFieldId_Aluno.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextFieldId_Aluno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldId_Aluno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldId_Aluno.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("RG");

        jTextFieldRG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRGFocusLost(evt);
            }
        });
        jTextFieldRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jDateChooserDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(148, 148, 148))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(190, 190, 190))
                            .addComponent(jTextFieldNome))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel11))
                                        .addGap(170, 170, 170))
                                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jCheckBoxAtivo)))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldId_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldId_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBusca))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel20)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbSair)
                    .addComponent(jbLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        validaremail();
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "Confirma ?");

        if (option == JOptionPane.YES_OPTION) {

            if (jComboBoxDependente.getSelectedItem().toString().equals("Selecione")) {
                JOptionPane.showMessageDialog(rootPane, "Selecione se o Aluno é Dependente ou Não!!");
                jComboBoxDependente.requestFocus();

            } else if (jFormattedTextFieldCPF.getText().equals("   .   .   -  ") && jComboBoxDependente.getSelectedItem().toString().equals("Não")) {
                JOptionPane.showMessageDialog(rootPane, "Digite o CPF!!");
                jFormattedTextFieldCPF.requestFocus();
            } else if (jComboBoxDependente.getSelectedItem().toString().equals("Sim") && jTextFieldNomeTitular.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Faça a Busca do Titular antes de Prosseguir!!");
                jButtonBusca.requestFocus();
            } else if (jComboBoxDependente.getSelectedItem().toString().equals("Sim") && jFormattedTextFieldCPFTitular.getText().equals("   .   .   -  ")) {
                JOptionPane.showMessageDialog(rootPane, "O Aluno informado não é um Titular!!");

            } else if (!jFormattedTextFieldCPF.getText().equals("   .   .   -  ") && jFormattedTextFieldCPFTitular.getText().equals("   .   .   -  ") && jComboBoxDependente.getSelectedItem().toString().equals("Sim")) {
                JOptionPane.showMessageDialog(rootPane, "O Aluno informado não é um Titular!!");
                limparcamposTitular();
                jComboBoxDependente.requestFocus();

            } else {
                salvar();
            }
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparcampos();
        limparcamposTitular();
        jComboBoxDependente.setSelectedItem("Selecione");
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jFormattedTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFFocusLost
        CPF();
    }//GEN-LAST:event_jFormattedTextFieldCPFFocusLost

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed

    private void jTextFieldCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeFocusLost

    private void jTextFieldCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeActionPerformed

    private void jTextFieldEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoFocusLost

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldRGTitularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRGTitularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRGTitularFocusLost

    private void jTextFieldRGTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRGTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRGTitularActionPerformed

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jTextFieldNomeTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeTitularActionPerformed

    private void jFormattedTextFieldCPFTitularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFTitularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFTitularFocusLost

    private void jFormattedTextFieldCPFTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFTitularActionPerformed

    private void jTextFieldEmailTitularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailTitularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailTitularFocusLost

    private void jTextFieldEmailTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailTitularActionPerformed

    private void jComboBoxDependenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDependenteItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxDependente.getSelectedItem().toString().equals("Sim")) {
            jButtonBusca.setEnabled(true);
            jTextFieldRG.setEnabled(false);
            limparcamposTitular();
            jFormattedTextFieldCPF.setEnabled(false);
            jFormattedTextFieldCPF.setText(null);
        }
        if (jComboBoxDependente.getSelectedItem().toString().equals("Não")) {
            jButtonBusca.setEnabled(false);
            jTextFieldRG.setEnabled(true);
            limparcamposTitular();
            jFormattedTextFieldCPF.setEnabled(true);
            jFormattedTextFieldCPF.setText(null);
        }
        if (jComboBoxDependente.getSelectedItem().toString().equals("Selecione")) {
            jButtonBusca.setEnabled(false);
            limparcamposTitular();
            jFormattedTextFieldCPF.setEnabled(true);
            jFormattedTextFieldCPF.setText(null);
        }


    }//GEN-LAST:event_jComboBoxDependenteItemStateChanged

    private void jComboBoxDependenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxDependenteFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxDependenteFocusLost

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        // TODO add your handling code here:
//        limparCampos();
//        limparTabelaContrato();
//        limparTabelaParcelas();
        limparcamposTitular();
        if (jComboBoxDependente.getSelectedItem().toString().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione se o Aluno é Dependente !");
            jComboBoxDependente.requestFocus();
        }
        if (jComboBoxDependente.getSelectedItem().toString().equals("Não")) {
            JOptionPane.showMessageDialog(null, "Não é possivel ");
            jComboBoxDependente.requestFocus();
        }

        JDPesquisaGlobalAluno pesquisa = new JDPesquisaGlobalAluno(null, rootPaneCheckingEnabled);
        pesquisa.setLocationRelativeTo(null);
        pesquisa.setVisible(true);

    }//GEN-LAST:event_jButtonBuscaActionPerformed

    private void jTextFieldIDTitularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDTitularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDTitularFocusLost

    private void jTextFieldIDTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDTitularActionPerformed

    private void jButtonBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonBuscaFocusLost
        // TODO add your handling code here:
        limparcamposTitular();
        buscarID();

    }//GEN-LAST:event_jButtonBuscaFocusLost

    private void jTextFieldIDTitularCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldIDTitularCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldIDTitularCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        buscarID_Aluno();
    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRGFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRGFocusLost

    private void jTextFieldRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRGActionPerformed

    private void limparcampos() {
        jTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jTextFieldEmail.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldCidade.setText("");
        jTextFieldBairro.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldRGTitular.setText("");
        jDateChooserDataNasc.setDate(null);

    }

    private void limparcamposTitular() {
        jFormattedTextFieldCPFTitular.setText(null);
        jTextFieldNomeTitular.setText("");
        jTextFieldEmailTitular.setText("");
        jFormattedTextFieldTelefoneTitular.setText("");
        jTextFieldIDTitular.setText("");
        jTextFieldRGTitular.setText("");

    }

    public void validaremail() {
        if (jTextFieldEmail.getText().isEmpty()) {

        } else if ((jTextFieldEmail.getText().contains("@")) && (jTextFieldEmail.getText().contains(".")) && (!jTextFieldEmail.getText().contains(" "))) {
            String usuario = new String(jTextFieldEmail.getText().substring(0, jTextFieldEmail.getText().lastIndexOf('@')));
            String dominio = new String(jTextFieldEmail.getText().substring(jTextFieldEmail.getText().lastIndexOf('@') + 1, jTextFieldEmail.getText().length()));
            if ((usuario.length() >= 1) && (!usuario.contains("@")) && (dominio.contains(".")) && (!dominio.contains("@")) && (dominio.indexOf(".") >= 1) && (dominio.lastIndexOf(".") < dominio.length() - 1)) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite um email valido!!");
            jTextFieldEmail.requestFocus();

        }
    }

    private boolean validarcamposvazios() {

        if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor digite um nome!", "Digite um nome", WIDTH);
            jTextFieldNome.requestFocus();

//        } else if (jComboBoxDependente.getSelectedItem().toString().equals("Não")) {
//            JOptionPane.showMessageDialog(null, "Por favor digite um CPF!", "Digite um CPF", WIDTH);
//            jFormattedTextFieldCPF.requestFocus();
        } else if (jTextFieldRGTitular.getText().equals(" ª")) {
            JOptionPane.showMessageDialog(null, "Por favor digite o RG!", "Digite o RG", WIDTH);
            jTextFieldRGTitular.requestFocus();
        } else if (jFormattedTextFieldTelefone.getText().equals("(  )     -    ")) {
            JOptionPane.showMessageDialog(null, "Por favor digite um Telefone!", "Digite um Telefone", WIDTH);
            jFormattedTextFieldTelefone.requestFocus();
        } else if (jTextFieldEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor digite um email!", "Digite um email", WIDTH);
            jTextFieldEmail.requestFocus();
        } else if (jTextFieldCidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor digite a Cidade!", "Digite a Cidade", WIDTH);
            jTextFieldEndereco.requestFocus();
        } else if (jTextFieldEndereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor digite O Endereço!", "Digite o Endereço", WIDTH);
            jTextFieldEndereco.requestFocus();
        } else if (jDateChooserDataNasc.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor digite A Data de Nascimento!", "Digite a data de Nascimento", WIDTH);
            jDateChooserDataNasc.requestFocus();

        } else {
//            JOptionPane.showMessageDialog(null, " Funcionario " + jTextFieldNovoNome.getText() + " atualizado");
            return false;
        }

        return true;
    }

    public void salvar() {
        if (validarcamposvazios() == false) {
            System.out.println("dddddd    ");
            AlunoBean alunos = new AlunoBean();
            AlunoDAO dao = new AlunoDAO();
            try {

                Date data = jDateChooserDataNasc.getDate();
                SimpleDateFormat df;
                df = new SimpleDateFormat("dd/MM/yyyy");
                df.format(new Date(System.currentTimeMillis()));
                String dataF = df.format(data);
                alunos.setNome(jTextFieldNome.getText());
                alunos.setCpf(jFormattedTextFieldCPF.getText());
                alunos.setEmail(jTextFieldEmail.getText());
                alunos.setTelefone(jFormattedTextFieldTelefone.getText());
                alunos.setCidade(jTextFieldCidade.getText());
                alunos.setBairro(jTextFieldBairro.getText());
                alunos.setEndereco(jTextFieldEndereco.getText());
                alunos.setRg(jTextFieldRG.getText());
                System.out.println("sdasdasdasdasdasdasdas");
                alunos.setData_nasc(dataF);
                System.out.println("q");
                String cpf = jFormattedTextFieldCPF.getText();
                System.out.println(cpf);
                System.out.println("eaaaaaaae    ");

                if (jCheckBoxAtivo.isSelected()) {
                    ativo = 1;
                } else {
                    ativo = 0;
                }
                if (jFormattedTextFieldCPF.getText().equals("   .   .   -  ")) {
                    alunos.setAtivo(ativo);
                    alunos.setId_titular(Integer.parseInt(jTextFieldIDTitular.getText()));
                     alunos.setRg(jTextFieldRGTitular.getText());
                    dao.inserir2(alunos);

//                    limparcampos();
//                    limparcamposTitular();
                    this.dispose();
                    JDCadAluno telacadaluno = new JDCadAluno(null, rootPaneCheckingEnabled);
                    telacadaluno.setLocationRelativeTo(null);
                    telacadaluno.setVisible(true);
                    jComboBoxDependente.setSelectedItem("Selecione");
                    jTextFieldNome.requestFocus();
                } else if (dao.existeCPF(cpf) == true) {
                    System.out.println("else    ");
                    JOptionPane.showMessageDialog(null, "Aluno já cadastrado para este CPF!! ");
                    jFormattedTextFieldCPF.requestFocus();
                } else {
                    System.out.println("else    ");
                    alunos.setId_titular(Integer.parseInt(jTextFieldId_Aluno.getText()));
                    alunos.setAtivo(ativo);
                    dao.inserir(alunos);
                    buscarID_Aluno2();
//                        limparcampos();
//                        limparcamposTitular();
                    this.dispose();
                    JDCadAluno telacadaluno = new JDCadAluno(null, rootPaneCheckingEnabled);
                    telacadaluno.setLocationRelativeTo(null);
                    telacadaluno.setVisible(true);
                    jComboBoxDependente.setSelectedItem("Selecione");
                    jTextFieldNome.requestFocus();
                }
            } catch (HeadlessException | ClassNotFoundException | NumberFormatException e) {

            }
        }
    }

    public void buscarID_Aluno2() {
        iniciarBD();
        int id_titular;

        try {
            AlunoBean aluno = new AlunoBean();
            AlunoDAO dao = new AlunoDAO();

            con = ConexaoFactory.getConnection();
            rsListar = stmtListar.executeQuery("SELECT * FROM cad_aluno");
            if (rsListar.last()) {

                id_titular = rsListar.getInt("id_aluno");
                System.out.println(id_titular);
                aluno.setId_titular(id_titular);

                dao.alteraId_Titular(aluno);
                System.out.println("src.JDCadAluno.buscarID_Aluno2()");
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro function buscarID_aluno2 em JDCadAlauno");
        }

    }

    public void buscarID_Aluno() {
        iniciarBD();
        try {
            con = ConexaoFactory.getConnection();
            rsListar = stmtListar.executeQuery("SELECT * FROM cad_aluno");
            if (rsListar.last()) {
                int valor = rsListar.getInt("id_aluno");
                id_aluno = valor + 1;
                jTextFieldId_Aluno.setText(Integer.toString(id_aluno));
            }
            if (!rsListar.last()) {
                jTextFieldId_Aluno.setText("1");
            }
        } catch (Exception e) {
        }

    }

    private void buscarID() {
        try {

//            limparCamposDadosContrato();
//            liberarTodosCamposContrato();
            AlunoBean aluno = new AlunoBean();
            aluno.setAtivo(JDPesquisaGlobalAluno.id_titular);
            iniciarBD();
            rsListar = stmtListar.executeQuery("SELECT * FROM cad_aluno WHERE id_aluno='" + aluno.getAtivo() + "'");

            if (rsListar.next()) {
                jTextFieldIDTitular.setText(rsListar.getString(1));
                jTextFieldNomeTitular.setText(rsListar.getString(2));
                jTextFieldEmailTitular.setText(rsListar.getString(9));
                jFormattedTextFieldTelefoneTitular.setText(rsListar.getString(5));
                jFormattedTextFieldCPFTitular.setText(rsListar.getString(7));
                jTextFieldRGTitular.setText(rsListar.getString(8));

            }
        } catch (SQLException ex) {

        }
    }

    private void iniciarBD() {
        try {
            con = ConexaoFactory.getConnection();
            stmtListar = con.createStatement();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
        }
    }

    private void lookandfell() {
        try {

            UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ParseException | UnsupportedLookAndFeelException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o tema = " + erro);
        }
    }

    public void CPF() {
        try {
            if (jFormattedTextFieldCPF.getText().equals("   .   .   -  ")) {

            }
            if (jFormattedTextFieldCPF.getText().contains("." + "-")) {

            } else {

                String cpf = jFormattedTextFieldCPF.getText();

                String S1, S2, S3, S4, S5, S6, S7, S8, S9, confere = "";
                int N1, N2, N3, N4, N5, N6, N7, N8, N9, verificador1, verificador2;
                S1 = cpf.substring(0, 1);
                N1 = Integer.parseInt(S1);
                S2 = cpf.substring(1, 2);
                N2 = Integer.parseInt(S2);
                S3 = cpf.substring(2, 3);
                N3 = Integer.parseInt(S3);
                S4 = cpf.substring(4, 5);
                N4 = Integer.parseInt(S4);
                S5 = cpf.substring(5, 6);
                N5 = Integer.parseInt(S5);
                S6 = cpf.substring(6, 7);
                N6 = Integer.parseInt(S6);
                S7 = cpf.substring(8, 9);
                N7 = Integer.parseInt(S7);
                S8 = cpf.substring(9, 10);
                N8 = Integer.parseInt(S8);
                S9 = cpf.substring(10, 11);
                N9 = Integer.parseInt(S9);

                verificador1 = (N1 * 10 + N2 * 9 + N3 * 8 + N4 * 7 + N5 * 6 + N6 * 5 + N7 * 4 + N8 * 3 + N9 * 2);
                if ((verificador1 % 11) < 2) {
                    verificador1 = 0;
                } else {
                    verificador1 = 11 - (verificador1 % 11);
                }
                verificador2 = (N1 * 11 + N2 * 10 + N3 * 9 + N4 * 8 + N5 * 7 + N6 * 6 + N7 * 5 + N8 * 4 + N9 * 3 + verificador1 * 2);
                if ((verificador2 % 11) < 2) {
                    verificador2 = 0;
                } else {
                    verificador2 = 11 - (verificador2 % 11);
                }

                confere = (S1 + S2 + S3 + "." + S4 + S5 + S6 + "." + S7 + S8 + S9 + "-" + verificador1 + "" + verificador2);
                if (cpf.equals("000.000.000-00") || cpf.equals("111.111.111-11")
                        || cpf.equals("222.222.222-22") || cpf.equals("333.333.333-33")
                        || cpf.equals("444.444.444-44") || cpf.equals("555.555.555-55")
                        || cpf.equals("666.666.666-66") || cpf.equals("777.777.777-77")
                        || cpf.equals("888.888.888-88") || cpf.equals("999.999.999-99")
                        || (cpf.length() != 14)) {
                    JOptionPane.showMessageDialog(null, "CPF INCORRETO !!");
                    jFormattedTextFieldCPF.requestFocus();
                } else if (confere.equals(cpf)) {

                } else {
                    JOptionPane.showMessageDialog(null, "Por Favor Digite um CPF Valido!!");
                    jFormattedTextFieldCPF.requestFocus();
                }

            }
        } catch (NumberFormatException e) {

        }
    }

    private void liberaCamposTitular() {

        jTextFieldEmailTitular.setEnabled(true);
        jFormattedTextFieldCPFTitular.setEnabled(true);
        jTextFieldRGTitular.setEnabled(true);
        jTextFieldNomeTitular.setEnabled(true);
        jFormattedTextFieldTelefoneTitular.setEnabled(true);

    }

    private void bloqueiaCamposTitular() {

        jTextFieldEmailTitular.setEnabled(false);
        jFormattedTextFieldCPFTitular.setEnabled(false);
        jTextFieldRGTitular.setEnabled(false);
        jTextFieldNomeTitular.setEnabled(false);
        jFormattedTextFieldTelefoneTitular.setEnabled(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCadAluno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCadAluno dialog = new JDCadAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JCheckBox jCheckBoxAtivo;
    private javax.swing.JComboBox<String> jComboBoxDependente;
    private com.toedter.calendar.JDateChooser jDateChooserDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFTitular;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneTitular;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmailTitular;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldIDTitular;
    private javax.swing.JTextField jTextFieldId_Aluno;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeTitular;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldRGTitular;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSair;
    // End of variables declaration//GEN-END:variables
}
