/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import com.birosoft.liquid.LiquidLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaPlainLookAndFeel;
import factory.ConexaoFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.plaf.synth.SynthLookAndFeel;
import javax.swing.table.DefaultTableModel;
import net.sourceforge.napkinlaf.NapkinLookAndFeel;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Ronaldo Pedro
 */
public class JFTelaPrincipal extends javax.swing.JFrame {

    JFLogin telalogin = new JFLogin();
    ConexaoFactory conecta = new ConexaoFactory();
//    public static String look_and_fell = ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    private java.sql.Connection con;
    private java.sql.Statement stmtListar;
    private java.sql.ResultSet rsListar;

    /**
     * Creates new form JFTelaPrincipal
     */
    public JFTelaPrincipal() {
        initComponents();
        lookandfell();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jLabelUser.setText(telalogin.nomeuser);
        dataRender1.setVisible(false);
        precoRender1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jLabelUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableContratos = new javax.swing.JTable();
        dataRender1 = new util.DataRender();
        precoRender1 = new util.PrecoRender();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGerEstoque = new javax.swing.JMenu();
        jMenuItemGerAlunos = new javax.swing.JMenuItem();
        jMenuItemGerFuncionarios = new javax.swing.JMenuItem();
        jMenuItemCadPlanos1 = new javax.swing.JMenuItem();
        jMenuItemCadPlanos2 = new javax.swing.JMenuItem();
        jMenuItemCadPlanos3 = new javax.swing.JMenuItem();
        jMenuItemCadPlanos4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadAluno = new javax.swing.JMenuItem();
        jMenuItemCadFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadFuncionario1 = new javax.swing.JMenuItem();
        jMenuItemCadFuncionario2 = new javax.swing.JMenuItem();
        jMenuMovimentação = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItemBaixaLctoPagar = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItemBaixaLctoReceber = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemRelatorioAlunos = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemAlterarSenha = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItemSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movi Mente - Menu Principal");
        setBackground(java.awt.Color.white);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/delete_button.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logout.png"))); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("<Usuario>");

        jTextFieldData.setEditable(false);
        jTextFieldData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldHora.setEditable(false);
        jTextFieldHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setText("USUARIO");
        jLabelUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUserMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CAIXA");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText("Contratos em Atraso");

        JTableContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Titular", "CPF", "E-mail", "Telefone", "Plano", "Dias Atraso", "Vencimento", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableContratos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTableContratos);
        if (JTableContratos.getColumnModel().getColumnCount() > 0) {
            JTableContratos.getColumnModel().getColumn(0).setMinWidth(50);
            JTableContratos.getColumnModel().getColumn(0).setPreferredWidth(50);
            JTableContratos.getColumnModel().getColumn(0).setMaxWidth(50);
            JTableContratos.getColumnModel().getColumn(2).setMinWidth(100);
            JTableContratos.getColumnModel().getColumn(2).setPreferredWidth(100);
            JTableContratos.getColumnModel().getColumn(2).setMaxWidth(100);
            JTableContratos.getColumnModel().getColumn(6).setCellRenderer(dataRender1);
            JTableContratos.getColumnModel().getColumn(7).setMinWidth(85);
            JTableContratos.getColumnModel().getColumn(7).setPreferredWidth(85);
            JTableContratos.getColumnModel().getColumn(7).setMaxWidth(85);
            JTableContratos.getColumnModel().getColumn(7).setCellRenderer(dataRender1);
            JTableContratos.getColumnModel().getColumn(8).setMinWidth(100);
            JTableContratos.getColumnModel().getColumn(8).setPreferredWidth(100);
            JTableContratos.getColumnModel().getColumn(8).setMaxWidth(100);
            JTableContratos.getColumnModel().getColumn(8).setCellRenderer(precoRender1);
        }

        jButton1.setText("Atualizar Tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jMenuGerEstoque.setText("Gerenciar");
        jMenuGerEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemGerAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/group_2.png"))); // NOI18N
        jMenuItemGerAlunos.setText("Alunos");
        jMenuItemGerAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerAlunosActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItemGerAlunos);

        jMenuItemGerFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/employees.png"))); // NOI18N
        jMenuItemGerFuncionarios.setText("Usuarios");
        jMenuItemGerFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerFuncionariosActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItemGerFuncionarios);

        jMenuItemCadPlanos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/album.png"))); // NOI18N
        jMenuItemCadPlanos1.setText("Planos");
        jMenuItemCadPlanos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPlanos1ActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItemCadPlanos1);

        jMenuItemCadPlanos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/album.png"))); // NOI18N
        jMenuItemCadPlanos2.setText("Modalidades");
        jMenuItemCadPlanos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPlanos2ActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItemCadPlanos2);

        jMenuItemCadPlanos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/report-vendor.png"))); // NOI18N
        jMenuItemCadPlanos3.setText("Novo Contrato - Aluno");
        jMenuItemCadPlanos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPlanos3ActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItemCadPlanos3);

        jMenuItemCadPlanos4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/report-vendor.png"))); // NOI18N
        jMenuItemCadPlanos4.setText("Novo Contrato - Empresa");
        jMenuItemCadPlanos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPlanos4ActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItemCadPlanos4);

        jMenuItem6.setText("Contas a Pagar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItem6);

        jMenuItem7.setText("Contas a Receber");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuGerEstoque.add(jMenuItem7);

        jMenuBar1.add(jMenuGerEstoque);

        jMenu1.setText("Cadastros");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemCadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/group_2.png"))); // NOI18N
        jMenuItemCadAluno.setText("Alunos");
        jMenuItemCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadAluno);

        jMenuItemCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/employees.png"))); // NOI18N
        jMenuItemCadFuncionario.setText("Usuarios");
        jMenuItemCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadFuncionario);

        jMenuItemCadFuncionario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/employees.png"))); // NOI18N
        jMenuItemCadFuncionario1.setText("Bancos");
        jMenuItemCadFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionario1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadFuncionario1);

        jMenuItemCadFuncionario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/factory.png"))); // NOI18N
        jMenuItemCadFuncionario2.setText("Empresas");
        jMenuItemCadFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadFuncionario2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadFuncionario2);

        jMenuBar1.add(jMenu1);

        jMenuMovimentação.setText("Financeiro");
        jMenuMovimentação.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/report-vendor.png"))); // NOI18N
        jMenuItem1.setText("Baixar Contrato");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuMovimentação.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/rsz_1464092855_money_dollar.png"))); // NOI18N
        jMenuItem2.setText("Caixa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuMovimentação.add(jMenuItem2);

        jMenuItem4.setText("Lançamento a Pagar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuMovimentação.add(jMenuItem4);

        jMenuItemBaixaLctoPagar.setText("Baixa de Lançamentos a Pagar");
        jMenuItemBaixaLctoPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBaixaLctoPagarActionPerformed(evt);
            }
        });
        jMenuMovimentação.add(jMenuItemBaixaLctoPagar);

        jMenuItem5.setText("Lançamento a Receber");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuMovimentação.add(jMenuItem5);

        jMenuItemBaixaLctoReceber.setText("Baixa de Lançamentos a Receber");
        jMenuItemBaixaLctoReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBaixaLctoReceberActionPerformed(evt);
            }
        });
        jMenuMovimentação.add(jMenuItemBaixaLctoReceber);

        jMenuBar1.add(jMenuMovimentação);

        jMenu3.setText("Relatórios");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItemRelatorioAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/relatorioosss.png"))); // NOI18N
        jMenuItemRelatorioAlunos.setText("Relatorios");
        jMenuItemRelatorioAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioAlunosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemRelatorioAlunos);

        jMenuBar1.add(jMenu3);

        jMenuOpcoes.setText("Opções");
        jMenuOpcoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1464092981_application-pgp-signature.png"))); // NOI18N
        jMenuItemAlterarSenha.setText("Alterar Senha");
        jMenuItemAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarSenhaActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItemAlterarSenha);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/check.png"))); // NOI18N
        jMenuItem3.setText("Alterar Valor Multa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(jMenuItem3);

        jMenuBar1.add(jMenuOpcoes);

        jMenuSobre.setText("Sobre");
        jMenuSobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemSistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/1464093089_window-system.png"))); // NOI18N
        jMenuItemSistema.setText("Sistema");
        jMenuItemSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSistemaActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItemSistema);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 477, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                    .addComponent(jTextFieldData)))))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUser)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(dataRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogout)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Sair do Sistema ?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        efetuarLogoff();

    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        datinha();
        jLabel1.setText("Olá, Bem Vindo (a) " + telalogin.nomelogado + " !");
        compararData();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jMenuItemSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSistemaActionPerformed
        JDSobre jdSobre = new JDSobre(this, rootPaneCheckingEnabled);
        jdSobre.setLocationRelativeTo(null);
        jdSobre.setVisible(true);
    }//GEN-LAST:event_jMenuItemSistemaActionPerformed

    private void jMenuItemAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarSenhaActionPerformed
        JDAlterarSenha jDalterarSenha = new JDAlterarSenha(this, rootPaneCheckingEnabled);
        jDalterarSenha.setLocationRelativeTo(null);
        jDalterarSenha.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarSenhaActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemRelatorioAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioAlunosActionPerformed
        //        JFRelatorios jFRelatorios = new JFRelatorios();
        //        jFRelatorios.setLocationRelativeTo(null);
        //        jFRelatorios.setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioAlunosActionPerformed

    private void jMenuItemCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionarioActionPerformed
        JDCadUsuario telacadfuncionario = new JDCadUsuario(null, rootPaneCheckingEnabled);
        telacadfuncionario.setLocationRelativeTo(null);
        telacadfuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFuncionarioActionPerformed

    private void jMenuItemCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadAlunoActionPerformed
        JDCadAluno telacadaluno = new JDCadAluno(null, rootPaneCheckingEnabled);
        telacadaluno.setLocationRelativeTo(null);
        telacadaluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadAlunoActionPerformed

    private void jMenuItemCadPlanos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPlanos3ActionPerformed
        // TODO add your handling code here:
        JDAPM apm = new JDAPM(this, rootPaneCheckingEnabled);
        apm.setLocationRelativeTo(null);
        apm.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadPlanos3ActionPerformed

    private void jMenuItemCadPlanos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPlanos2ActionPerformed
        // TODO add your handling code here:
        JDCadModalidades modalidade = new JDCadModalidades(this, rootPaneCheckingEnabled);
        modalidade.setLocationRelativeTo(null);
        modalidade.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadPlanos2ActionPerformed

    private void jMenuItemCadPlanos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPlanos1ActionPerformed
        // TODO add your handling code here:
        JDCadPlanos cadPlanos = new JDCadPlanos(this, rootPaneCheckingEnabled);
        cadPlanos.setLocationRelativeTo(null);
        cadPlanos.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadPlanos1ActionPerformed

    private void jMenuItemGerFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerFuncionariosActionPerformed
        JDCRUDUsuario telaCRUDfuncionario = new JDCRUDUsuario(null, rootPaneCheckingEnabled);
        telaCRUDfuncionario.setLocationRelativeTo(null);
        telaCRUDfuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemGerFuncionariosActionPerformed

    private void jMenuItemGerAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerAlunosActionPerformed
        JDCRUDAluno telaCRUDAluno = new JDCRUDAluno(null, rootPaneCheckingEnabled);
        telaCRUDAluno.setLocationRelativeTo(null);
        telaCRUDAluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemGerAlunosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDBaixaContrato telaBaixa = new JDBaixaContrato(null, rootPaneCheckingEnabled);
        telaBaixa.setLocationRelativeTo(null);
        telaBaixa.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JDMovimentoCaixa movicaixa = new JDMovimentoCaixa(this, rootPaneCheckingEnabled);
        movicaixa.setLocationRelativeTo(null);
        movicaixa.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JDMulta multa = new JDMulta(this, rootPaneCheckingEnabled);
        multa.setLocationRelativeTo(null);
        multa.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemCadFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionario1ActionPerformed
        // TODO add your handling code here:
        JDCadBanco banco = new JDCadBanco(this, rootPaneCheckingEnabled);
        banco.setLocationRelativeTo(null);
        banco.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFuncionario1ActionPerformed

    private void jLabelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUserMouseClicked
        // TODO add your handling code here:
        this.dispose();
        JFLogin login = new JFLogin();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_jLabelUserMouseClicked

    private void jMenuItemCadFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadFuncionario2ActionPerformed
        // TODO add your handling code here:
        JDCadEmpresa empresa = new JDCadEmpresa(this, rootPaneCheckingEnabled);
        empresa.setLocationRelativeTo(null);
        empresa.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadFuncionario2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JDLancReceber lancRec = new JDLancReceber(this, rootPaneCheckingEnabled);
        lancRec.setLocationRelativeTo(null);
        lancRec.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        JDLancPagar lancPagar = new JDLancPagar(this, rootPaneCheckingEnabled);
        lancPagar.setLocationRelativeTo(null);
        lancPagar.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemBaixaLctoPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBaixaLctoPagarActionPerformed
        // TODO add your handling code here:
        JDBaixaPagar baixaPagar = new JDBaixaPagar(this, rootPaneCheckingEnabled);
        baixaPagar.setLocationRelativeTo(null);
        baixaPagar.setVisible(true);
    }//GEN-LAST:event_jMenuItemBaixaLctoPagarActionPerformed

    private void jMenuItemBaixaLctoReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBaixaLctoReceberActionPerformed
        // TODO add your handling code here:
        JDBaixaReceber baixaReceber = new JDBaixaReceber(this, rootPaneCheckingEnabled);
        baixaReceber.setLocationRelativeTo(null);
        baixaReceber.setVisible(true);
    }//GEN-LAST:event_jMenuItemBaixaLctoReceberActionPerformed

    private void jMenuItemCadPlanos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPlanos4ActionPerformed
        // TODO add your handling code here:
        JDAPMEmpresa apm = new JDAPMEmpresa(this, rootPaneCheckingEnabled);
        apm.setLocationRelativeTo(null);
        apm.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadPlanos4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        JDLancPagarBaixa lancPagar = new JDLancPagarBaixa(this, rootPaneCheckingEnabled);
        lancPagar.setLocationRelativeTo(null);
        lancPagar.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        JDLancReceberBaixa lancRec = new JDLancReceberBaixa(this, rootPaneCheckingEnabled);
        lancRec.setLocationRelativeTo(null);
        lancRec.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        ((DefaultTableModel) JTableContratos.getModel()).setNumRows(0);
        ((DefaultTableModel) JTableContratos.getModel()).setNumRows(50);
        compararData();
    }//GEN-LAST:event_formFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ((DefaultTableModel) JTableContratos.getModel()).setNumRows(0);
        ((DefaultTableModel) JTableContratos.getModel()).setNumRows(50);
        compararData();
    }//GEN-LAST:event_jButton1ActionPerformed

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            jTextFieldHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }

    }

    private void datinha() {
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("EEEE, d' de 'MMMM' de 'yyyy");
        jTextFieldData.setText(formato.format(dataSistema));

        Timer timer = new Timer(1000, new hora());
        timer.start();
    }

    private void efetuarLogoff() {
        int option = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Deslogar-se ?");
        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
            JFLogin login = new JFLogin();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        } else {

        }
    }

    private void iniciarBD() {
        try {
            con = ConexaoFactory.getConnection();
            stmtListar = con.createStatement();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
        }
    }

    private boolean compararData() {
        try {
            Date hoje = new Date();
            String dataFormatada = new SimpleDateFormat("yyyy-MM-dd").format(hoje);

            iniciarBD();
            rsListar = stmtListar.executeQuery("SELECT\n"
                    + "     DATEDIFF(CURRENT_DATE,parcela_contrato.data_vencimento) AS dias_atraso,\n"
                    + "     contrato.`id_contrato` AS contrato_id_contrato,\n"
                    + "     contrato.`id_titular` AS contrato_id_titular,\n"
                    + "     contrato.`valor_mensal` AS contrato_valor_mensal,\n"
                    + "     cad_aluno.`id_aluno` AS cad_aluno_id_aluno,\n"
                    + "     cad_aluno.`nome` AS cad_aluno_nome,\n"
                    + "     cad_aluno.`telefone` AS cad_aluno_telefone,\n"
                    + "     cad_aluno.`cpf` AS cad_aluno_cpf,\n"
                    + "     cad_aluno.`email` AS cad_aluno_email,\n"
                    + "     parcela_contrato.`id_parcela_contrato` AS parcela_contrato_id_parcela_contrato,\n"
                    + "     parcela_contrato.`id_contrato` AS parcela_contrato_id_contrato,\n"
                    + "     parcela_contrato.`numero_parcela` AS parcela_contrato_numero_parcela,\n"
                    + "     parcela_contrato.`valor_parcela` AS parcela_contrato_valor_parcela,\n"
                    + "     parcela_contrato.`data_vencimento` AS parcela_contrato_data_vencimento,\n"
                    + "     parcela_contrato.`data_baixa` AS parcela_contrato_data_baixa,\n"
                    + "     parcela_contrato.`usuario` AS parcela_contrato_usuario,\n"
                    + "     parcela_contrato.`tipo_pagamento` AS parcela_contrato_tipo_pagamento,\n"
                    + "     parcela_contrato.`tipo_entrada` AS parcela_contrato_tipo_entrada,\n"
                    + "     parcela_contrato.`valor_total` AS parcela_contrato_valor_total,\n"
                    + "     cad_plano.`id_plano` AS cad_plano_id_plano,\n"
                    + "     cad_plano.`nome` AS cad_plano_nome,\n"
                    + "     contrato.`id_plano` AS contrato_id_plano\n"
                    + "FROM\n"
                    + "     `cad_aluno` cad_aluno INNER JOIN `contrato` contrato ON cad_aluno.`id_aluno` = contrato.`id_titular`\n"
                    + "     AND cad_aluno.`id_titular` = contrato.`id_titular`\n"
                    + "     INNER JOIN `parcela_contrato` parcela_contrato ON contrato.`id_contrato` = parcela_contrato.`id_contrato`\n"
                    + "     INNER JOIN `cad_plano` cad_plano ON contrato.`id_plano` = cad_plano.`id_plano` WHERE parcela_contrato.data_vencimento<CURRENT_DATE and parcela_contrato.data_baixa IS NULL");
            montarTabela();

        } catch (SQLException e) {
        }
        return true;
    }

    private void montarTabela() {
        int linha = 0;
        try {
            while (rsListar.next()) {
                int id_titulo = rsListar.getInt("parcela_contrato_id_parcela_contrato");
                String titular = rsListar.getString("cad_aluno_nome");
                String cpf = rsListar.getString("cad_aluno_cpf");
                String email = rsListar.getString("cad_aluno_email");
                String telefone = rsListar.getString("cad_aluno_telefone");
                String plano = rsListar.getString("cad_plano_nome");
                String dias_atraso = rsListar.getString("dias_atraso");
                Object data_vencimento = rsListar.getObject("parcela_contrato_data_vencimento");
                Double valor = rsListar.getDouble("parcela_contrato_valor_parcela");

                JTableContratos.getModel().setValueAt(id_titulo, linha, 0);
                JTableContratos.getModel().setValueAt(titular, linha, 1);
                JTableContratos.getModel().setValueAt(cpf, linha, 2);
                JTableContratos.getModel().setValueAt(email, linha, 3);
                JTableContratos.getModel().setValueAt(telefone, linha, 4);
                JTableContratos.getModel().setValueAt(plano, linha, 5);
                JTableContratos.getModel().setValueAt(dias_atraso, linha, 6);
                JTableContratos.getModel().setValueAt(data_vencimento, linha, 7);
                JTableContratos.getModel().setValueAt(valor, linha, 8);
                linha++;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
        }
    }

    private void lookandfell() {
        try {

            UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar o tema = " + erro);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableContratos;
    private util.DataRender dataRender1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGerEstoque;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemAlterarSenha;
    private javax.swing.JMenuItem jMenuItemBaixaLctoPagar;
    private javax.swing.JMenuItem jMenuItemBaixaLctoReceber;
    private javax.swing.JMenuItem jMenuItemCadAluno;
    private javax.swing.JMenuItem jMenuItemCadFuncionario;
    private javax.swing.JMenuItem jMenuItemCadFuncionario1;
    private javax.swing.JMenuItem jMenuItemCadFuncionario2;
    private javax.swing.JMenuItem jMenuItemCadPlanos1;
    private javax.swing.JMenuItem jMenuItemCadPlanos2;
    private javax.swing.JMenuItem jMenuItemCadPlanos3;
    private javax.swing.JMenuItem jMenuItemCadPlanos4;
    private javax.swing.JMenuItem jMenuItemGerAlunos;
    private javax.swing.JMenuItem jMenuItemGerFuncionarios;
    private javax.swing.JMenuItem jMenuItemRelatorioAlunos;
    private javax.swing.JMenuItem jMenuItemSistema;
    private javax.swing.JMenu jMenuMovimentação;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldHora;
    private util.PrecoRender precoRender1;
    // End of variables declaration//GEN-END:variables
}
